
TRUNCATE TABLE public.gifts;

INSERT INTO public.gifts (name, already_owned) VALUES
('Cama', true),
('Cabeceira da cama', true),
('Mesa de jantar', true),
('Painel da TV', true),
('TV', true),
('Armário de cozinha', true),
('Máquina de lavar', true),
('Fogão cooktop', true),
('Geladeira', false),
('Sofá', false),
('Guarda-roupas', false),
('Base/balcão do cooktop', false),
('Tanquinho de lavar roupa', false),
('Panela de pressão', false),
('Jogo de panelas', false),
('Frigideira', false),
('Assadeiras', false),
('Air fryer', false),
('Forno elétrico', false),
('Micro-ondas', false),
('Sanduicheira', false),
('Liquidificador', false),
('Cafeteira', false),
('Escorredor de pratos', false),
('Jogo de pratos', false),
('Copos', false),
('Talheres', false),
('Potes organizadores', false),
('Cobertas', false),
('Cortinas', false),
('Toalhas', false),
('Tábua de passar roupa', false),
('Ventilador', false),
('Tapetes', false);
